numpy es una libreria para python muy util y manejada en el manejo del data science

In [2]:
import numpy as np
from numpy import pi

In [13]:
#arreglos
#es importante saber que cuando se declara un arreglo para numpy se tiene que enviar como parametro una secuencia unica como argumento (lista) y no multiples elementos separados por coma
np.array([12,15,125,35,53,65,45,78])#denotacions para crear un arreglo con numpy
a= np.array([21,54,32,65,78,89,56,45,12,32,65,98])
print(f'posicion 4: {a[4]}')#los arreglos de numpy son iterables, por lo que en esta caso estamos mostrando la posicions 4 del arreglo (tomando en cuetna que comienza desde 0)
#se puede iterar con la denotacion de slices
print(f'desde la posicion 3 hasta el final {a[3:]}')#desde la posicion 3 hasta el final
print(f'posicion del 3 al 7 {a[3:7]}')
print(f'imprecion con intervalos cada 3 {a[::3]}')

posicion 4: 78
desde la posicion 3 hasta el final [65 78 89 56 45 12 32 65 98]
posicion del 3 al 7 [65 78 89 56]
imprecion con intervalos cada 3 [21 65 56 32]


In [89]:
#arreglos de dos dimensiones
"""
el objeto principal de numpy es un arreglo multidimensional homogeneo
este es una tabla de elementos (por lo general numeros), todos del mismos tipo, indezados como una TUPLA de enteros no negativos (non-negative).

en numpy las dimendiones de un arreglo son llamadas axes (trad dir: hachas)
por ejemplo un arreglo [1,2,3] tiene un eje y este ejes diene una longitud de 3. entonces:
el numero de filas en numpy se define como axes y el numero de columnas en numpy se define con la longitud
"""
mat = np.array([[1,2,3,4],[5,6,7,8]])
print(f'arreglo bidimencional: \n{mat}')
#para poder ver la ultima fila del arreglo
print(f'ultima fila: {mat[-1]}') 

arreglo bidimencional: 
[[1 2 3 4]
 [5 6 7 8]]
ultima fila: [5 6 7 8]


In [52]:
#metodos de array
vect = np.array([21,54,874,65,231,54,21,87])
mat = np.array([[1,2,3,4],[5,6,7,8]])
#retornar el numero de dimensiones de un arreglo
print(f'ver el numero de dimensiones(axes): {mat.ndim} ; {vect.ndim}')
#retornar la "forma" del arreglo (retorna una tuple)
#para una matriz retorna una tupla con (filas,columnas)
#para un vector retorna su longitud en forma de tupla (longitud,)
print(f'forma de los arreglos: {mat.shape},{vect.shape}')
#para retornar el numero de elementos of un arreglo
print(f'numero de elementos {mat.size} ; {vect.size}')
#retorna el tipo de elementos que contiene el arreglo
print(f'tipo de los elementos en los arreglos: {mat.dtype} ; {vect.dtype}')
#retornar el tamano en bytes de cada elemento en el arreglo, por ejemplo: un arreglo de elementos de tipo float64 tiene un (itemzise) de 8=(64/8) mientras que un elemento de tipo complex32 tiene un (itemzise) de 4 = (32/8)
print(f'tamano en bytes de los elementos: {vect.itemsize} ; {vect.itemsize} ')
#retorna la direccion en la que se encuentra almancenado el arreglo (primera posicion), este atributo por lo general no es utilizado dado que numpy da acceso a los elementos en el arreglo usando indexaciones faciles
print(f'direcciones: {mat.data} ; {vect.data}')

ver el numero de dimensiones(axes): 2 ; 1
forma de los arreglos: (2, 4),(8,)
numero de elementos 8 ; 8
tipo de los elementos en los arreglos: int32 ; int32
tamano en bytes de los elementos: 4 ; 4 
direcciones: <memory at 0x000001E639582128> ; <memory at 0x000001E639538A08>


In [54]:
#otra forma de declarar arreglos
#arreglos bidimensionales
matuple = np.array([(1,2,3,4,5),(5,6,7,8,9)])
print(matuple)
#el tipo de elementos en la matriz tambien se puede especificar
matcom = np.array([[1,2],[3,4]], dtype=complex)
print(matcom)

[[1 2 3 4 5]
 [5 6 7 8 9]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [63]:
#crear arreglos predefinidos de forma dinamica (con metodos de numpy)
#arreglos de zeros
ceros = np.zeros(5)
print(f'arreglo de ceros: {ceros}')
ceros = np.zeros((4,5))
print(f'arreglo bidimencional de ceros:\n {ceros}')
#arreglo de unos
unos = np.ones(5)
print(f'arreglo de unos: {unos}')
unos = np.ones((4,5))
print(f'arreglo bidimensional de unos: \n{unos}')
#arreglos de numeros aleatorios
aleatorio = np.empty((2,3)) #los parametros ingresados representan las filas y columnas
print(f'vector de aleatorios:\n{aleatorio}')
#arreglos a partir de rangos
rango = np.arange(10,30,5)
print(f'arreglos a partir de rangos: {rango}')
#cuando se quiere crear un vector con un rango en el cual se emplean flotantes, no se recomienta mucho usar (arange) dado que no siempre es posible predecir el numero de elemento debido a la presicion en los decimales, para esto se creo la funcion linspace en el cual se define el intevalo deseado y el numero de elementos que se quiere
rango_flotante = np.linspace(0,2*pi,100)
print(f'linspace:\n{rango_flotante}')

arreglo de ceros: [0. 0. 0. 0. 0.]
arreglo bidimencional de ceros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
arreglo de unos: [1. 1. 1. 1. 1.]
arreglo bidimensional de unos: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
vector de aleatorios:
[[1.14587773e-312 1.37929726e-312 1.88857625e-312]
 [9.54898106e-313 6.79038653e-313 2.07955588e-312]]
arreglos a partir de rangos: [10 15 20 25]
linspace:
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.0463

In [11]:
#transformacion dimensional de los arreglos
a = np.array([[65,12,54,78],[52,41,25,36],[48,59,26,15],[42,52,35,68]])
print(a, a.shape)
print(a.ravel())#retorna el arreglo bidimensional en uno unidimensional
b= a.ravel()
c= b.reshape(8,2)#pasa de arreglo unidimensional a bidimensional
print(c)
print(c.T)#modifica las filas por columnas

[[65 12 54 78]
 [52 41 25 36]
 [48 59 26 15]
 [42 52 35 68]] (4, 4)
[65 12 54 78 52 41 25 36 48 59 26 15 42 52 35 68]
[[65 12]
 [54 78]
 [52 41]
 [25 36]
 [48 59]
 [26 15]
 [42 52]
 [35 68]]
[[65 54 52 25 48 26 42 35]
 [12 78 41 36 59 15 52 68]]


In [100]:
#operaciones basicas (unidimensionales)
a = np.array([54,323,65,98])
b = np.arange(4)
c = a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<158)
#redondear los valores flotantes
#numpy redondea los valores en el valor inferior
mat = np.array([[1.5,2.6,3.7],[4.2,5.3,6.1],[-7.5,-8.1,-9.8]])
print(mat)
print(np.floor(mat))

[ 54 322  63  95]
[0 1 4 9]
[-5.58789049  5.51401534  8.26828679 -5.73381872]
[ True False  True  True]
[[ 1.5  2.6  3.7]
 [ 4.2  5.3  6.1]
 [-7.5 -8.1 -9.8]]
[[  1.   2.   3.]
 [  4.   5.   6.]
 [ -8.  -9. -10.]]


In [ ]:
#concatenar matrices
a= np.array([[1.,9.],[2.,3.]])

In [80]:
#operaciones basicas (bidimensionales)
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B) #producto punto
print(A@B) #producto matricial
print(A.dot(B)) #otra forma de hacer producto matricial
print(A.sum())#sumatoria
print(B.min())#valor minimo
print(B.max())#valor maximo
print(B.cumsum(axis=1))#crea una matriz en la que va haciendo una sumatoria acumulada a lo largo de cada fila


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
3
0
4
[[2 2]
 [3 7]]


In [88]:
#las matrices multidimencionales pueden tener un indice por eje, estosn indices se dan como una tupla separada por comas
#se puede crear un arreglos multidimencional enviando los indices a una funcion
def f(x,y):
    return 10*x+y
funt = np.fromfunction(f,shape=(5,4))
print(funt)

[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]
 [30. 31. 32. 33.]
 [40. 41. 42. 43.]]


In [3]:
#iterando sobre un arreglo multidimensional
#por fila
mat = np.array([[54,21,65,32],[45,12,78,56],[85,52,65,54],[25,48,53,52]])
print(mat)
print('\niteraciones filas:')
for row in mat:
    print(row)
print('\niteraciones elementos:')
for element in mat.flat:
    print(element)

[[54 21 65 32]
 [45 12 78 56]
 [85 52 65 54]
 [25 48 53 52]]

iteraciones filas:
[54 21 65 32]
[45 12 78 56]
[85 52 65 54]
[25 48 53 52]

iteraciones elementos:
54
21
65
32
45
12
78
56
85
52
65
54
25
48
53
52
